### ISSUE TITLE
Where to put the bot token??

### ISSUE THREAD

**Issue by zero69-weeb** [CTK-WARRIOR/Discord-Profile-Card-#1]
Where to put the bot token?? please reply

**Comment by zedxos** [comment]
> Where to put the bot token?? please reply

Bruh wth its not a bot its html

**Comment by macedonga** [comment]
Lmao what

**Comment by 1mlm** [comment]
:joy: wtfff

**Comment by macedonga** [comment]
:-|

**Comment by Yonle** [comment]
Let me say this, This is not a bot code.

If you don't know Javascript or HTML, Then please learn it before using this repo.
